services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - ${MONGO_EXPRESS_WEBUI_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${ADMIN_USERNAME}:${ADMIN_PASSWORD}@mongo:27017
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo

    rabbitmq:
        image: rabbitmq:3.13.2-management
        container_name: rabbitmq
        ports:
            - ${RABBITMQ_AMQP_PORT}:5672
            - ${RABBITMQ_WEBUI_PORT}:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${ADMIN_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${ADMIN_PASSWORD}
        restart: unless-stopped

    livechat:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            MONGO_PORT: ${MONGO_PORT}
            RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
            EXPRESS_PORT: ${EXPRESS_PORT}
            FRONTEND_PORT: ${FRONTEND_PORT}
        ports:
            - ${EXPRESS_PORT}:${EXPRESS_PORT}
        depends_on:
            - rabbitmq
            - mongo

volumes:
    mongo-data:
